database.name: TP_GESTION_PRODUIT

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}?autoReconnect=true&useSSL=false
    username: root
    password: mysql_rootFF
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect